---
settings:
  name: StorageGRID
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documenti StorageGRID
    url: "/index.html"
  - title: Note di rilascio
    entries:
    - title: Novità
      url: "/whats-new.html"
    - title: Problemi noti
      url: "/reference-known-issues.html"
  - title: Inizia subito
    entries:
    - title: Scopri i sistemi StorageGRID
      url: "/task-discover-storagegrid.html"
  - title: Gestire i sistemi StorageGRID
    entries:
    - title: Visualizza i tuoi sistemi StorageGRID
      url: "/task-view-storagegrid.html"
    - title: Visualizzare e aggiornare i certificati StorageGRID
      url: "/task-manage-certificates.html"
    - title: Amministrare StorageGRID utilizzando la vista avanzata
      url: task-administer-storagegrid.html
    - title: Utilizza i servizi dati NetApp con StorageGRID
      url: "/task-enable-data-services.html"
    - title: Rimuovere un ambiente di lavoro
      url: "/task-remove-storagegrid.html"
  - title: Conoscenza e supporto
    entries:
    - title: Registrati per ricevere assistenza
      url: "/task-support-registration.html"
    - title: Richiedi assistenza
      url: "/task-get-help.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
