---
sidebar: sidebar 
permalink: reference-known-issues.html 
keywords: issues, known issues, bugs, errors 
summary: 'I problemi noti identificano i problemi che potrebbero impedire l"utilizzo corretto di questa versione del prodotto.' 
---
= Problemi noti
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
I problemi noti identificano i problemi che potrebbero impedire l'utilizzo corretto di questa versione del prodotto.



== I nomi visualizzati aggiornati non vengono visualizzati in BlueXP 

Se si utilizza la procedura di ridenominazione per definire un nuovo nome di visualizzazione per un sito o una griglia, il nuovo nome di visualizzazione non viene riflesso nell'ambiente di lavoro BlueXP . L'ambiente di lavoro continua a mostrare il nome del sistema e non il nuovo nome visualizzato.



== Errore durante il filtraggio degli avvisi

Quando si utilizza la visualizzazione avanzata, il filtraggio del contenuto della pagina Avvisi genera un errore.



== Errore durante la modifica della connessione di federazione della griglia

Quando si utilizza la visualizzazione avanzata, potrebbe verificarsi un errore di timeout del gateway durante la modifica di una connessione di federazione della griglia.
