---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, storagegrid' 
summary: Scopri le novità della gestione dei sistemi StorageGRID in BlueXP. 
---
= Novità della gestione StorageGRID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Scopri le novità della gestione dei sistemi StorageGRID in BlueXP.



== 12 maggio 2025



=== Ruoli di accesso BlueXP necessari

Ora è necessario uno dei seguenti ruoli di accesso per visualizzare, scoprire o gestire StorageGRID in BlueXP: *Amministratore organizzazione*, *Amministratore cartella o progetto*, *Amministratore archiviazione* o *Specialista integrità archiviazione*. link:https://docs.netapp.com/us-en/bluexp/reference-iam-predefined-roles.html["Scopri di più sui ruoli di accesso BlueXP."^]



== 7 agosto 2024



=== Nuova vista avanzata

A partire da StorageGRID 11,8, è possibile utilizzare la familiare interfaccia di gestione griglia per gestire il sistema StorageGRID da BlueXP .

https://docs.netapp.com/us-en/bluexp-storagegrid/task-administer-storagegrid.html["Informazioni su come amministrare StorageGRID utilizzando la visualizzazione avanzata"].



=== Possibilità di rivedere e approvare il certificato dell'interfaccia di gestione StorageGRID

È ora possibile esaminare e approvare un certificato dell'interfaccia di gestione StorageGRID quando si rileva il sistema StorageGRID da BlueXP . È inoltre possibile esaminare e approvare il certificato più recente dell'interfaccia di gestione StorageGRID in una griglia scoperta.

https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["Informazioni su come esaminare e approvare il certificato del server durante il rilevamento del sistema."]



== 18 settembre 2022



=== Supporto per StorageGRID

Ora puoi scoprire i tuoi sistemi StorageGRID direttamente da BlueXP. Discovering StorageGRID ti offre una vista completa dei dati nel tuo multicloud ibrido.
